#!/bin/bash -l
#PBS -N compute_adjacency_mat
#PBS -l nodes=1:ppn=8
#PBS -l walltime=22:00:00
#PBS -M ali39@jhu.edu
#PBS -m abe
#PBS -q dque
#PBS -S /bin/bash
#PBS -d /home/ali/adamli/fragility_dataanalysis/server
#PBS -e /home/ali/adamli/fragility_dataanalysis/server/_log/test.err
#PBS -o /home/ali/adamli/fragility_dataanalysis/server/_log/test.out
cd /home/ali/adamli/fragility_dataanalysis/server

for i in `seq 0 $numWins`; do
	proc=$(($i%8))
	tempi=$(($i+1))
	pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/server/dev/connectivity/computeConnectivity.sh $proc $patient $radius $winSize $stepSize $tempi &
done