#!/bin/bash -l
#PBS -N compute_adjacency_mat_ezt
#PBS -l nodes=1:ppn=8
#PBS -l walltime=22:00:00
#PBS -M ali39@jhu.edu
#PBS -m abe
#PBS -q dque
#PBS -S /bin/bash
#PBS -d /home/ali/adamli/fragility_dataanalysis/server
#PBS -e /home/ali/adamli/fragility_dataanalysis/server/_log/test.err
#PBS -o /home/ali/adamli/fragility_dataanalysis/server/_log/test.out
cd /home/ali/adamli/fragility_dataanalysis/server

# for proc in `seq 0 ${#patients[@]}`; do
# 	patient=${patients[proc]}
# 	pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/server/runAnalysis.sh $proc $patient $frequency_sampling $winSize $stepSize $radius $RUNCONNECTIVITY &
# done 

proc=0 
pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/server/runAnalysis.sh $proc $patient $RUNCONNECTIVITY &
wait


# echo $numTimes
# echo $patient
# for ((i=0; i<=numTimes; i++)); do
# 	proc= $i
# 	pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/server/runAnalysis.sh $proc $patient $RUNCONNECTIVITY &
# wait
