#!/bin/bash -l
#PBS -N compute_adjacency_mat
#PBS -l nodes=3:ppn=8
#PBS -l walltime=14:00:00
#PBS -M ali39@jhu.edu
#PBS -m abe
#PBS -q dque
#PBS -S /bin/bash
#PBS -d /home/ali/adamli/fragility_dataanalysis
#PBS -e /home/ali/adamli/fragility_dataanalysis/_log/test.err
#PBS -o /home/ali/adamli/fragility_dataanalysis/_log/test.out

source /etc/profile.modules
module load matlab/matlab2013a

# cd /projects/sarma/cluster_script_example
# runs the sleep function on all faulty nodes 
source run_all_pbs.sh

for proc in `seq 0 23` 
	pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/runAnalysis.sh $proc $patient_id $seizure_id $perturbationType &
done
wait