#!/bin/bash -l
#PBS -M ali39@jhu.edu
#PBS -m abe
#PBS -q dque
#PBS -S /bin/bash
#PBS -d /home/ali/adamli/fragility_dataanalysis/server/devFragility/
#PBS -e /home/ali/adamli/fragility_dataanalysis/server/devFragility/_log/test.err
#PBS -o /home/ali/adamli/fragility_dataanalysis/server/devFragility/_log/test.out
cd /home/ali/adamli/fragility_dataanalysis/server/devFragility/

for proc in `seq 1 8`; do
	currentWin=$(($currentNode+$proc))
	pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/server/devFragility/computeAnalysis.sh $proc $patient $currentWin $RUNCONNECTIVITY &
done