#!/bin/bash -l
#PBS -N compute_adjacency_mat
#PBS -l nodes=135:ppn=8
#PBS -l walltime=1:00:00
#PBS -M ali39@jhu.edu
#PBS -m abe
#PBS -q dque
#PBS -S /bin/bash
#PBS -d /home/ali/adamli/fragility_dataanalysis/server/devFragility/
#PBS -e /home/ali/adamli/fragility_dataanalysis/server/devFragility/_log/test.err
#PBS -o /home/ali/adamli/fragility_dataanalysis/server/devFragility/_log/test.out
cd /home/ali/adamli/fragility_dataanalysis/server/devFragility/

for proc in `seq 0 $numWins`; do
	# proc=$(($i%3))
	tempi=$(($i+1))
	pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/server/devFragility/computeAnalysis.sh $proc $patient $tempi $RUNCONNECTIVITY &
done