#!/bin/bash -l
#PBS -M ali39@jhu.edu
#PBS -m abe
#PBS -q dque
#PBS -S /bin/bash
#PBS -d /home/ali/adamli/fragility_dataanalysis/server/devFragility/
#PBS -e localhost:${PBS_O_WORKDIR}/_log/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/_log/${PBS_JOBNAME}.o${PBS_JOBID}

source /etc/profile.modules
module load matlab/matlab2013a

cd /home/ali/adamli/fragility_dataanalysis/server/devFragility/

for ((proc=0; proc <= ((${NprocperNode})); proc++))
do
	currentWin=$((${currentNode} + ${proc} + 1))
	pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/server/devFragility/computeAnalysis.sh ${proc} ${patient} ${currentWin} ${winSize} ${stepSize} ${radius} ${RUNCONNECTIVITY} &
done

# proc=${numWins}
# pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/server/devFragility/mergeAnalysis.sh ${proc} ${patient} ${winSize} ${stepSize} ${radius} ${RUNCONNECTIVITY} &