#!/bin/bash -l
#PBS -M ali39@jhu.edu
#PBS -m abe
#PBS -q dque
#PBS -S /bin/bash
#PBS -d /home/ali/adamli/fragility_dataanalysis/server/devVaryingWindows/preProcess/
#PBS -e localhost:${PBS_O_WORKDIR}/_log/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/_log/${PBS_JOBNAME}.o${PBS_JOBID}
source /etc/profile.modules
module load matlab/matlab2013a

cd /home/ali/adamli/fragility_dataanalysis/server/devVaryingWindows/preProcess/

# For each processor in node, compute certain channels
for ((proc=0; proc < ((${numChans})); proc++))
do
	currentChan=$((${proc} + 1))
	echo $currentChan
	pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/server/devVaryingWindows/preProcess/computeSpectralAnalysis.sh ${proc} ${patient} ${winSize} ${stepSize} ${currentChan} ${typeTransform} &
done

proc = ${numChans}
pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/server/devVaryingWindows/preProcess/mergeJobs.sh ${proc} ${patient} ${winSize} ${stepSize} ${typeTransform} &

wait