#!/bin/bash -l
#PBS -N compute_adjacency_mat_seeg
#PBS -l nodes=1:ppn=8
#PBS -l walltime=22:00:00
#PBS -M ali39@jhu.edu
#PBS -m abe
#PBS -q dque
#PBS -S /bin/bash
#PBS -d /home/ali/adamli/fragility_dataanalysis/server/devVaryingWindows/
#PBS -e /home/ali/adamli/fragility_dataanalysis/server/_log/test.err
#PBS -o /home/ali/adamli/fragility_dataanalysis/server/_log/test.out

# make sure to cd to the correct directory.
# also make sure PBS -d is the correct directory 
cd /home/ali/adamli/fragility_dataanalysis/server/devVaryingWindows/

proc=0 
pbsdsh -n $proc /home/ali/adamli/fragility_dataanalysis/server/devVaryingWindows/runAnalysis.sh $proc $patient $RUNCONNECTIVITY $winSize &
wait